import type { Metadata } from "next";
import type { CSSProperties } from "react";
import Image from "next/image";
import Link from "next/link";
import { getProductsHome } from "@/data/products";

export const metadata: Metadata = { title: "High-tech premium au Cameroun", description: "Découvrez les smartphones, ordinateurs et accessoires sélectionnés par CanarisTech." };

const categories = [["smartphone", "Smartphones"], ["laptop_mac", "Ordinateurs"], ["tablet_mac", "Tablettes"], ["headphones", "Écouteurs"], ["watch", "Montres"], ["cable", "Accessoires"], ["tv", "Téléviseurs"], ["sports_esports", "Gaming"]] as const;
const products = getProductsHome();
const Icon = ({ children, className = "", style }: { children: string; className?: string; style?: CSSProperties }) => <span aria-hidden="true" className={`material-symbols-outlined ${className}`} style={style}>{children}</span>;

export default function Home() { return <>
  <section className="relative flex min-h-[580px] items-center overflow-hidden bg-surface-container-low"><div className="absolute inset-0 bg-[url('https://lh3.googleusercontent.com/aida-public/AB6AXuDYLc1fZSSFVJhtFdi0FxgXGQ4MBSC62FqvHaksRn4Ig6Q4OfVVZOa5DbzDhwAtSLeq261BInBcvVxu7O5BLK979-kEkF-cxyPiUZK9OhwIA8gdkRdLYIkXEvDTgg0WIj6VDf1RcgIrCuuSVjU7PTGD66ls3nmu1nDUT63zIw4ZBN2oZKcRnMwrUvnXk6OyugJ73ATv-7AZo2uPFkWphKe7FOcACoN1hLQqfPoTEgxqcPfutHnCs0ePcA')] bg-cover bg-center opacity-20" /><div className="relative mx-auto w-full max-w-container px-5 py-20 lg:px-16"><div className="max-w-2xl"><p className="mb-4 text-sm font-bold uppercase tracking-[0.18em] text-primary">CanarisTech</p><h1 className="text-4xl font-bold tracking-tight text-on-surface sm:text-5xl sm:leading-tight">La technologie qui vous accompagne au quotidien.</h1><p className="mt-5 text-lg leading-8 text-on-surface-variant">Votre spécialiste high-tech premium.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/boutique" className="rounded-lg bg-primary-container px-6 py-3 font-semibold text-on-primary hover:bg-primary">Découvrir la boutique</Link><Link href="/contact" className="rounded-lg bg-[#25D366] px-6 py-3 font-semibold text-white hover:bg-[#1DA851]">Commander sur WhatsApp</Link></div></div></div></section>
  <section className="mx-auto max-w-container px-5 py-14 lg:px-16"><h2 className="text-2xl font-semibold tracking-tight">Catégories populaires</h2><div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">{categories.map(([icon, name]) => <Link href="/categories" key={name} className="flex min-h-32 flex-col items-center justify-center rounded-lg border border-outline-variant/40 bg-surface-container-lowest p-4 text-center shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Icon className="mb-2 text-4xl text-primary">{icon}</Icon><span className="text-sm font-semibold">{name}</span></Link>)}</div></section>
  <section className="mx-auto max-w-container px-5 pb-14 lg:px-16"><div className="flex items-baseline justify-between gap-4"><h2 className="text-2xl font-semibold tracking-tight">Produits populaires</h2><Link href="/boutique" className="text-sm font-semibold text-primary hover:underline">Voir la boutique</Link></div><div className="mt-7 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{products.map((product) => <article key={product.id} className="overflow-hidden rounded-lg border border-outline-variant/40 bg-surface-container-lowest shadow-sm transition hover:shadow-md cursor-pointer group"><Link href={`/produit/${product.slug}`} className="block"><div className="relative flex h-64 items-center justify-center bg-[#f5f7fa] p-5 group-hover:bg-[#f0f2f6] transition"><Image className="max-h-full w-auto object-contain" src={product.image} alt={`Photo du ${product.name}`} width={360} height={256} />{product.promo && <span className="absolute right-4 top-4 rounded-full bg-error px-3 py-1 text-xs font-bold text-on-error">Promo</span>}</div><div className="p-5"><h3 className="text-lg font-semibold">{product.name}</h3><p className="mt-2 flex items-center gap-1 text-sm text-on-surface-variant"><Icon className="text-base text-amber-500">star</Icon>{product.rating}</p><p className="mt-3 text-xl font-semibold text-primary">{new Intl.NumberFormat("fr-FR").format(product.price)} FCFA</p></div></Link><div className="px-5 pb-5"><Link href={`/produit/${product.slug}?action=whatsapp`} className="mt-5 flex justify-center rounded-lg bg-[#25D366] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#1DA851]">Commander sur WhatsApp</Link></div></article>)}</div></section>
  <section className="mx-auto max-w-container px-5 pb-16 lg:px-16"><div className="flex flex-col items-center justify-between gap-6 rounded-xl border border-primary/20 bg-inverse-surface p-8 text-center sm:p-10 md:flex-row md:text-left"><div><h2 className="text-3xl font-bold tracking-tight text-surface-bright">Les meilleures offres tech du moment</h2><p className="mt-3 text-surface-variant/80">Découvrez nos réductions exclusives.</p></div><Link href="/promotions" className="shrink-0 rounded-lg bg-primary-container px-6 py-3 font-semibold text-on-primary hover:bg-primary">Voir les promotions</Link></div></section>
</>; }
