"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

const navigation = [{ href: "/", label: "Accueil" }, { href: "/boutique", label: "Boutique" }, { href: "/promotions", label: "Promotions" }, { href: "/a-propos", label: "À propos" }, { href: "/contact", label: "Contact" }];
const Icon = ({ children }: { children: string }) => <span aria-hidden="true" className="material-symbols-outlined leading-none">{children}</span>;
export function Navbar() { const pathname = usePathname(); const [isOpen, setIsOpen] = useState(false); return <header className="fixed inset-x-0 top-0 z-50 border-b border-outline-variant/40 bg-surface/90 shadow-sm backdrop-blur-md"><div className="mx-auto flex h-20 max-w-container items-center justify-between px-5 lg:px-16"><Link href="/" className="flex items-center" aria-label="CanarisTech — Accueil"><Image src="/assets/logo.jpg" alt="CanarisTech Logo" width={50} height={50} className="h-12 w-auto" priority /></Link><nav aria-label="Navigation principale" className="hidden items-center gap-6 md:flex">{navigation.map((item) => <Link key={item.href} href={item.href} className={`border-b-2 pb-1 text-sm font-semibold transition-colors ${pathname === item.href ? "border-primary text-primary" : "border-transparent text-on-surface-variant hover:text-primary"}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-2 sm:gap-4"><button type="button" aria-label="Rechercher" className="rounded-md p-2 active:scale-95"><Icon>search</Icon></button><button type="button" aria-label="Voir le panier" className="rounded-md p-2 active:scale-95"><Icon>shopping_cart</Icon></button><Link href="/contact" className="hidden rounded-lg bg-primary-container px-4 py-2 text-sm font-semibold text-on-primary hover:bg-primary sm:block">Commander</Link><button type="button" aria-label={isOpen ? "Fermer le menu" : "Ouvrir le menu"} aria-expanded={isOpen} className="rounded-md p-2 md:hidden" onClick={() => setIsOpen(!isOpen)}><Icon>{isOpen ? "close" : "menu"}</Icon></button></div></div>{isOpen && <nav aria-label="Navigation mobile" className="border-t border-outline-variant/40 bg-surface px-5 py-4 md:hidden">{navigation.map((item) => <Link key={item.href} href={item.href} onClick={() => setIsOpen(false)} className={`block rounded-lg px-3 py-3 font-semibold ${pathname === item.href ? "bg-surface-container text-primary" : "text-on-surface-variant"}`}>{item.label}</Link>)}</nav>}</header>; }
